name: Build Android Binaries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install xgo
      run: go install github.com/crazy-max/xgo@latest

    - name: Download dependencies
      run: go mod tidy

    - name: Build for Android
      run: |
        xgo --targets=android/arm,android/arm64,android/386,android/amd64 -out speedtest-android .

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: android-binaries
        path: speedtest-android-android-*
