name: Build Android Binaries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [arm64, arm, 386, amd64]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      env:
        GOOS: android
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -o speedtest-android-${{ matrix.goarch }} speedtest.go

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: speedtest-android-${{ matrix.goarch }}
        path: speedtest-android-${{ matrix.goarch }}
