name: Build Android Binaries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [arm64, arm, 386, amd64]
        include:
          - goarch: arm
            goarm: 7
          - goarch: 386
            gomips: softfloat
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Download dependencies
      run: go mod tidy

    - name: Build
      env:
        GOOS: android
        GOARCH: ${{ matrix.goarch }}
        GOARM: ${{ matrix.goarm }}
        GOMIPS: ${{ matrix.gomips }}
        CGO_ENABLED: 0
      run: |
        go build -o speedtest-android-${{ matrix.goarch }} speedtest.go

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: speedtest-android-${{ matrix.goarch }}
        path: speedtest-android-${{ matrix.goarch }}
